name: issue809

parameters:
  frame:
    width: 7680
    height: 4320
  batch_size: 1
  output_frame:
    codec: hevc
    encoder_params:
      # 4.7 Mbps - module works normally on DS 7.0
      bitrate: 4700000

      # 100 Mbps - module works normally on DS 6.4, hangs on DS 7.0
      #bitrate: 100000000

      # 200 Mbps - module hangs after processing 150 frames
      #bitrate: 200000000
