# module name, required
name: source_shaper_sample

# base module parameters
parameters:
  # pipeline processing frame parameters
  frame:
    # custom frame shaper implementation
    shaper:
      module: samples.source_shaper_sample.custom_source_shaper
      class_name: CustomSourceShaper
      kwargs:
        sources:
          city-traffic:
            # original resolution: 1920x1080
            width: 1440
            height: 800
            padding:
              top: 160
              right: 80
          town-centre:
            # original resolution: 1280x720
            width: 960
            height: 544
            padding:
              left: 64
  draw_func:
    # the draw_func colors the frame paddings with the specified color
    module: samples.source_shaper_sample.overlay
    class_name: Overlay
    kwargs:
      color: [0, 0, 255, 255]
  output_frame:
    codec: ${oc.env:CODEC, 'h264'}
  batch_size: 1
