name: keypoint_detection

parameters:
  output_frame:
    codec: ${oc.env:CODEC, 'h264'}
  detector: yolov8n-pose
  draw_func:
    module: samples.keypoint_detection.overlay
    class_name: Overlay
  batch_size: 1

pipeline:
