# module name, required
name: opencv_cuda_bg_remover_mog2

# base module parameters
parameters:
  # pipeline processing frame parameters
  frame:
    width: 1280
    height: 720
  batch_size: 1
  # to check auxiliary streams' encoder
  auxiliary_encoders:
    - ${pipeline.elements[0].kwargs.codec_params}

# pipeline definition
pipeline:
  # source definition is skipped, zeromq source is used by default to connect with source adapters

  # define pipeline's main elements
  elements:
    - element: pyfunc
      # specify the pyfunc's python module
      module: samples.opencv_cuda_bg_remover_mog2.bgremover
      # specify the pyfunc's python class from the module
      class_name: BgRemover
      kwargs:
        # codec parameters for result stream (auxiliary stream)
        codec_params:
          codec: ${oc.env:CODEC, 'h264'}

  # sink definition is skipped, zeromq sink is used by default to connect with sink adapters
